#!/bin/bash

# Utilitaires Git pour automatisation GitHub

initialize_git_repo() {
    local project_dir=$1
    local project_name=$2
    
    print_info "Initialisation du dépôt Git..."
    
    cd "$project_dir"
    
    # Initialiser git si pas déjà fait
    if [ ! -d ".git" ]; then
        git init -b main
        print_success "Dépôt Git initialisé"
    fi
    
    # Copier le gitignore
    if [ -f "$SCRIPT_DIR/templates/.gitignore.template" ]; then
        cp "$SCRIPT_DIR/templates/.gitignore.template" .gitignore
        print_success "Fichier .gitignore créé"
    fi
    
    # Premier commit
    git add .
    git commit -m "🎉 Initial commit - Generated by Stackbuild

Project: $project_name
Stack: Spring Boot + Angular + PostgreSQL
Features: JWT Authentication, Docker, CI/CD

Generated with: https://github.com/votre-username/web-stack-cli" || true
    
    print_success "Premier commit créé"
    
    cd - > /dev/null
}

create_github_repo() {
    local project_dir=$1
    local project_name=$2
    local is_public=${3:-true}
    
    cd "$project_dir"
    
    print_info "Création du dépôt GitHub..."
    
    # Vérifier si gh CLI est installé
    if ! command -v gh &> /dev/null; then
        print_warning "GitHub CLI (gh) n'est pas installé"
        show_manual_github_steps "$project_name"
        cd - > /dev/null
        return 1
    fi
    
    # Vérifier l'authentification
    if ! gh auth status &> /dev/null; then
        print_info "Authentification GitHub requise..."
        gh auth login
    fi
    
    # Créer le repo
    local visibility_flag=""
    if [ "$is_public" = true ]; then
        visibility_flag="--public"
    else
        visibility_flag="--private"
    fi
    
    print_info "Création du dépôt $project_name..."
    
    if gh repo create "$project_name" \
        $visibility_flag \
        --source=. \
        --remote=origin \
        --description="Full-stack application: Spring Boot + Angular + PostgreSQL | Generated by web-stack-cli" \
        --push; then
        
        print_success "Dépôt GitHub créé et code poussé !"
        
        local repo_url=$(gh repo view --json url -q .url)
        print_info "URL du dépôt: $repo_url"
        
        # Sauvegarder les infos
        echo "GITHUB_REPO=$repo_url" > .github-info
        echo "GITHUB_REPO_NAME=$project_name" >> .github-info
        
        cd - > /dev/null
        return 0
    else
        print_error "Échec de la création du dépôt GitHub"
        show_manual_github_steps "$project_name"
        cd - > /dev/null
        return 1
    fi
}

setup_github_secrets() {
    local project_dir=$1
    
    cd "$project_dir"
    
    if [ ! -f ".github-info" ]; then
        print_error "Fichier .github-info introuvable"
        cd - > /dev/null
        return 1
    fi
    
    source .github-info
    
    print_info "Configuration des secrets GitHub..."
    
    # Demander les tokens/secrets
    echo ""
    print_info "Pour automatiser les déploiements, nous avons besoin de:"
    echo "  1. RENDER_API_KEY - Pour déployer le backend"
    echo "  2. NETLIFY_AUTH_TOKEN - Pour déployer le frontend"
    echo ""
    
    read -p "Voulez-vous configurer les secrets maintenant? (y/N) " -n 1 -r
    echo
    
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Vous pouvez les configurer plus tard avec:"
        echo "  gh secret set RENDER_API_KEY"
        echo "  gh secret set NETLIFY_AUTH_TOKEN"
        echo "  gh secret set NETLIFY_SITE_ID"
        cd - > /dev/null
        return 0
    fi
    
    # RENDER_API_KEY
    echo ""
    print_info "1. Render API Key"
    echo "   Obtenir sur: https://dashboard.render.com/account/api-keys"
    read -p "   Entrez votre RENDER_API_KEY (ou appuyez sur Entrée pour ignorer): " render_key
    
    if [ -n "$render_key" ]; then
        echo "$render_key" | gh secret set RENDER_API_KEY
        print_success "RENDER_API_KEY configuré"
        echo "RENDER_API_KEY=configured" >> .github-info
    fi
    
    # NETLIFY_AUTH_TOKEN
    echo ""
    print_info "2. Netlify Auth Token"
    echo "   Obtenir sur: https://app.netlify.com/user/applications/personal"
    read -p "   Entrez votre NETLIFY_AUTH_TOKEN (ou appuyez sur Entrée pour ignorer): " netlify_token
    
    if [ -n "$netlify_token" ]; then
        echo "$netlify_token" | gh secret set NETLIFY_AUTH_TOKEN
        print_success "NETLIFY_AUTH_TOKEN configuré"
        echo "NETLIFY_AUTH_TOKEN=configured" >> .github-info
    fi
    
    print_success "Configuration des secrets terminée"
    
    cd - > /dev/null
}

show_manual_github_steps() {
    local project_name=$1
    
    cat << EOF

📋 Création manuelle du dépôt GitHub:

Option A - Avec GitHub CLI:
  1. Installez GitHub CLI:
     - macOS: brew install gh
     - Linux: voir https://cli.github.com/manual/installation
     - Windows: voir https://cli.github.com/manual/installation
  
  2. Authentifiez-vous:
     gh auth login
  
  3. Créez le dépôt:
     gh repo create $project_name --public --source=. --remote=origin --push

Option B - Manuellement:
  1. Allez sur https://github.com/new
  2. Nom du repo: $project_name
  3. Ne créez pas de README, .gitignore ou LICENSE
  4. Créez le repo
  5. Puis dans votre terminal:
     git remote add origin https://github.com/VOTRE_USERNAME/$project_name.git
     git push -u origin main

EOF
}

push_to_remote() {
    local project_dir=$1
    local branch=${2:-main}
    
    cd "$project_dir"
    
    print_info "Push vers GitHub..."
    
    if ! git remote get-url origin &> /dev/null; then
        print_error "Aucun remote 'origin' configuré"
        cd - > /dev/null
        return 1
    fi
    
    if git push -u origin "$branch"; then
        print_success "Code poussé vers GitHub"
    else
        print_error "Échec du push"
        cd - > /dev/null
        return 1
    fi
    
    cd - > /dev/null
}

check_git_status() {
    local project_dir=$1
    
    cd "$project_dir"
    
    if [ -d ".git" ]; then
        print_success "Dépôt Git initialisé"
        
        if git remote get-url origin &> /dev/null; then
            local remote=$(git remote get-url origin)
            print_success "Remote configuré: $remote"
        else
            print_warning "Aucun remote configuré"
        fi
    else
        print_warning "Pas de dépôt Git"
    fi
    
    cd - > /dev/null
}

# Fonction pour vérifier et installer gh CLI si nécessaire
install_gh_cli() {
    if command -v gh &> /dev/null; then
        print_success "GitHub CLI déjà installé"
        return 0
    fi
    
    print_info "Installation de GitHub CLI..."
    
    local os=$(uname -s)
    
    case $os in
        Darwin)
            if command -v brew &> /dev/null; then
                brew install gh
                print_success "GitHub CLI installé"
            else
                print_error "Homebrew requis. Installez depuis: https://brew.sh"
                return 1
            fi
            ;;
        Linux)
            # Debian/Ubuntu
            if command -v apt-get &> /dev/null; then
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                sudo apt update
                sudo apt install gh -y
                print_success "GitHub CLI installé"
            else
                print_error "Distribution non supportée. Installez manuellement: https://cli.github.com"
                return 1
            fi
            ;;
        *)
            print_error "OS non supporté. Installez manuellement: https://cli.github.com"
            return 1
            ;;
    esac
}

# Fonction pour obtenir les infos du repo GitHub
get_github_info() {
    local project_dir=$1
    
    cd "$project_dir"
    
    if [ -f ".github-info" ]; then
        source .github-info
        echo "Repository: $GITHUB_REPO"
        echo "Name: $GITHUB_REPO_NAME"
    elif git remote get-url origin &> /dev/null; then
        local remote=$(git remote get-url origin)
        echo "Remote: $remote"
    else
        echo "Aucune information GitHub disponible"
    fi
    
    cd - > /dev/null
}