# Configuration par défaut du générateur Web Stack CLI

# Configuration du projet
project:
  name: my-app
  description: "Full-stack application generated by Web Stack CLI"
  version: "1.0.0"

# Configuration de la stack technique
stack:
  backend:
    type: spring  # Options: spring, node, fastapi
    port: 8080
    features:
      - rest-api
      - jwt-auth
      - cors
      - swagger
      - validation
    dependencies:
      spring:
        - spring-boot-starter-web
        - spring-boot-starter-data-jpa
        - spring-boot-starter-security
        - spring-boot-starter-validation
        - lombok
        - jjwt
      node:
        - express
        - jsonwebtoken
        - bcrypt
        - cors
        - dotenv
        - mongoose  # si MongoDB
        - pg  # si PostgreSQL
      fastapi:
        - fastapi
        - uvicorn
        - python-jose
        - passlib
        - python-multipart
        - sqlalchemy
        - psycopg2-binary  # si PostgreSQL
  
  frontend:
    type: angular  # Options: angular, react, vue
    port: 4200
    features:
      - routing
      - http-client
      - auth-guard
      - interceptors
      - lazy-loading
    dependencies:
      angular:
        - "@angular/core"
        - "@angular/router"
        - "@angular/common/http"
        - "@angular/forms"
        - rxjs
      react:
        - react
        - react-dom
        - react-router-dom
        - axios
        - "@tanstack/react-query"
      vue:
        - vue
        - vue-router
        - axios
        - pinia
  
  database:
    type: postgres  # Options: postgres, mysql, mongodb
    port: 5432
    features:
      - migrations
      - seeds
    config:
      postgres:
        version: "15-alpine"
        database: "appdb"
        username: "appuser"
        password: "changeme"
      mysql:
        version: "8"
        database: "appdb"
        username: "appuser"
        password: "changeme"
      mongodb:
        version: "6"
        database: "appdb"
        username: "appuser"
        password: "changeme"

# Configuration de l'authentification
auth:
  enabled: true
  type: jwt  # Options: jwt, oauth2
  jwt:
    secret: "your-secret-key-change-in-production"
    expiration: 86400  # 24 heures en secondes
    refresh_expiration: 604800  # 7 jours
  endpoints:
    login: "/api/auth/login"
    register: "/api/auth/register"
    refresh: "/api/auth/refresh"
    logout: "/api/auth/logout"
    profile: "/api/auth/profile"

# Configuration Docker
docker:
  compose_version: "3.8"
  networks:
    - app-network
  volumes:
    - db-data
  restart_policy: "unless-stopped"

# Configuration du déploiement
deployment:
  backend:
    platform: render  # Options: render, heroku, railway
    plan: free
    region: frankfurt  # EU region
    config:
      build_command: "auto"  # Détecté automatiquement
      start_command: "auto"  # Détecté automatiquement
      health_check_path: "/api/health"
      auto_deploy: true
    env_vars:
      - DATABASE_URL
      - JWT_SECRET
      - CORS_ORIGIN
  
  frontend:
    platform: netlify  # Options: netlify, vercel
    plan: free
    config:
      build_command: "auto"  # Détecté automatiquement
      publish_directory: "dist"  # ou "build" pour React
      auto_deploy: true
    env_vars:
      - VITE_API_URL  # ou REACT_APP_API_URL
      - VITE_AUTH_DOMAIN
  
  database:
    platform: render  # Ou service externe
    plan: free
    backup: true

# Configuration CI/CD
ci_cd:
  platform: github-actions  # Options: github-actions, gitlab-ci
  triggers:
    - push
    - pull_request
  branches:
    - main
    - develop
  jobs:
    - lint
    - test
    - build
    - deploy
  environments:
    - development
    - staging
    - production

# Configuration des tests
testing:
  backend:
    framework: junit  # ou jest, pytest
    coverage_threshold: 80
  frontend:
    framework: jasmine  # ou jest, vitest
    coverage_threshold: 80
  e2e:
    framework: cypress  # ou playwright
    enabled: false

# Configuration de la documentation
documentation:
  api:
    format: openapi  # OpenAPI/Swagger
    version: "3.0"
    title: "API Documentation"
    description: "Generated API documentation"
  readme: true
  changelog: true

# Configuration des hooks
hooks:
  pre_generate:
    - validate_config
    - check_dependencies
  post_generate:
    - format_code
    - initialize_git
  pre_deploy:
    - run_tests
    - build_assets
  post_deploy:
    - notify_success
    - update_docs

# Paramètres avancés
advanced:
  code_style:
    backend:
      spring: google-java-format
      node: prettier + eslint
      fastapi: black + flake8
    frontend:
      angular: prettier + eslint
      react: prettier + eslint
      vue: prettier + eslint
  
  git:
    initialize: true
    initial_branch: main
    gitignore: true
  
  security:
    helmet: true  # Pour Node.js
    rate_limiting: true
    cors_strict: false  # false en dev, true en prod
  
  performance:
    caching: true
    compression: true
    cdn: false  # À activer manuellement
  
  monitoring:
    health_checks: true
    logging:
      level: info  # debug, info, warn, error
      format: json
    metrics: false  # Désactivé pour garder simple